alias clean='make clean'
alias pull='git pull'
alias load='insmod hw3secws.ko'
alias unload='rmmod hw3secws'
alias reset='rm -rf /root/FireWall; git clone https://github.com/Itay1007/FireWall'
alias class='cd /sys/class'
alias rules='cd /sys/class/fw/rules'
alias log='cd /dev/log'